import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/(conponents)/Header/header";
import Container from "@/app/(conponents)/Container/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gen Expert",
  description: "Generated by 4106677",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header/>
      <Container>
          <main>{children}</main>
      </Container>
      </body>
    </html>
  );
}
