import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/(components)/Header/header";
import Container from "@/app/(components)/Container/container";
import SheetDataProvider from "@/app/(components)/SheetDataProvider";
import ClientLayout from "./ClientLayout";
import Modal from "@/app/(components)/Modal/modal";

const roboto = localFont({
    src: "../../public/fonts/Roboto.ttf",
    variable: "--font-roboto",
    display: "swap",
});

const caviarDreams = localFont({
    src: "../../public/fonts/caviar_dreams/CaviarDreams.ttf",
    variable: "--font-caviar-dreams",
    display: "swap",
});

const caviarDreamsBold = localFont({
    src: "../../public/fonts/caviar_dreams/CaviarDreams_Bold.ttf",
    variable: "--font-caviar-dreams-bold",
    display: "swap",
});

export const metadata = {
  title: "Gen Expert",
  description: "Generated by 4106677",
};

export default async function RootLayout({children, params}) {
    return (
        <html lang="en">
        <body className={`${caviarDreams.variable} ${caviarDreamsBold.variable} ${roboto.variable}`}>
        <ClientLayout>
            <SheetDataProvider >
                <Header />
                <Container>
                    <main>{children}</main>
                </Container>
                {/*<Footer/>*/}
                <Modal/>
            </SheetDataProvider>
        </ClientLayout>
        </body>
        </html>
    );
}
